services:
  backend:
    image: ghcr.io/borschtapp/smetana:latest
    restart: unless-stopped
    env_file: .env
#    depends_on:
#      postgres:
#        condition: service_healthy
    volumes:
      - ./data:/data

# database is optional, read .env.example or README.md for more details
#  postgres:
#    image: pgvector/pgvector:pg18-trixie
#    restart: unless-stopped
#    env_file: .env
#    volumes:
#      - ./pgdata:/var/lib/postgresql
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
