### Create new book
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@borsch.app",
  "password": "adminadmin"
}

### Create a new account
POST {{host}}/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@borsch.app",
  "password": "adminadmin"
}
