### Get user details
GET {{host}}/user
Accept: application/json
Authorization: Bearer {{access_token}}

### Update user name
PATCH {{host}}/user
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "new name",
  "email": "admin@borsch.app"
}

### Delete the user
DELETE {{host}}/user
Content-Type: application/json
Authorization: Bearer {{access_token}}
